name: AutoCorrect Website Files

on:
  pull_request:
    paths:
      - '.github/**'
      - 'crater-website/src/**'        
      - 'crater-website/content/**'

jobs:
  autocorrect:
    name: Run AutoCorrect on Website
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: AutoCorrect and Commit (for internal PRs)
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: huacnlee/autocorrect-action@main
        with:
          working-directory: ./crater-website
          args: --fix

      - name: Commit changes (for internal PRs)
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style(website): Auto-correct files by autocorrect-action"
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>

      - name: Lint Check (for forked PRs)
        if: github.event.pull_request.head.repo.full_name != github.repository
        uses: huacnlee/autocorrect-action@main
        with:
          working-directory: ./crater-website
          args: --lint